// Code generated by qtc from "base_page.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/base_page.qtpl:1
package templates

//line templates/base_page.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/base_page.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/base_page.qtpl:2
type Page interface {
//line templates/base_page.qtpl:2
	Title() string
//line templates/base_page.qtpl:2
	StreamTitle(qw422016 *qt422016.Writer)
//line templates/base_page.qtpl:2
	WriteTitle(qq422016 qtio422016.Writer)
//line templates/base_page.qtpl:2
	Body() string
//line templates/base_page.qtpl:2
	StreamBody(qw422016 *qt422016.Writer)
//line templates/base_page.qtpl:2
	WriteBody(qq422016 qtio422016.Writer)
//line templates/base_page.qtpl:2
}

// Page prints a page implementing Page interface.

//line templates/base_page.qtpl:9
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
//line templates/base_page.qtpl:9
	qw422016.N().S(`
<html>
	<head>
		<title>`)
//line templates/base_page.qtpl:12
	p.StreamTitle(qw422016)
//line templates/base_page.qtpl:12
	qw422016.N().S(`</title>
	</head>
	<body>
		`)
//line templates/base_page.qtpl:15
	p.StreamBody(qw422016)
//line templates/base_page.qtpl:15
	qw422016.N().S(`
	</body>
</html>
`)
//line templates/base_page.qtpl:18
}

//line templates/base_page.qtpl:18
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
//line templates/base_page.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/base_page.qtpl:18
	StreamPageTemplate(qw422016, p)
//line templates/base_page.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line templates/base_page.qtpl:18
}

//line templates/base_page.qtpl:18
func PageTemplate(p Page) string {
//line templates/base_page.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/base_page.qtpl:18
	WritePageTemplate(qb422016, p)
//line templates/base_page.qtpl:18
	qs422016 := string(qb422016.B)
//line templates/base_page.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/base_page.qtpl:18
	return qs422016
//line templates/base_page.qtpl:18
}

//line templates/base_page.qtpl:20
type BasePage struct{}

//line templates/base_page.qtpl:21
func (p *BasePage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/base_page.qtpl:21
	qw422016.N().S(`This is a base title`)
//line templates/base_page.qtpl:21
}

//line templates/base_page.qtpl:21
func (p *BasePage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/base_page.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/base_page.qtpl:21
	p.StreamTitle(qw422016)
//line templates/base_page.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line templates/base_page.qtpl:21
}

//line templates/base_page.qtpl:21
func (p *BasePage) Title() string {
//line templates/base_page.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/base_page.qtpl:21
	p.WriteTitle(qb422016)
//line templates/base_page.qtpl:21
	qs422016 := string(qb422016.B)
//line templates/base_page.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/base_page.qtpl:21
	return qs422016
//line templates/base_page.qtpl:21
}

//line templates/base_page.qtpl:22
func (p *BasePage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/base_page.qtpl:22
	qw422016.N().S(`This is a base body`)
//line templates/base_page.qtpl:22
}

//line templates/base_page.qtpl:22
func (p *BasePage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/base_page.qtpl:22
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/base_page.qtpl:22
	p.StreamBody(qw422016)
//line templates/base_page.qtpl:22
	qt422016.ReleaseWriter(qw422016)
//line templates/base_page.qtpl:22
}

//line templates/base_page.qtpl:22
func (p *BasePage) Body() string {
//line templates/base_page.qtpl:22
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/base_page.qtpl:22
	p.WriteBody(qb422016)
//line templates/base_page.qtpl:22
	qs422016 := string(qb422016.B)
//line templates/base_page.qtpl:22
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/base_page.qtpl:22
	return qs422016
//line templates/base_page.qtpl:22
}
