// Code generated by qtc from "input_form.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/input_form.qtpl:1
package templates

//line templates/input_form.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/input_form.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/input_form.qtpl:2
type MainPage struct{}

//line templates/input_form.qtpl:6
func (p *MainPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/input_form.qtpl:6
	qw422016.N().S(`
	Main Page
`)
//line templates/input_form.qtpl:8
}

//line templates/input_form.qtpl:8
func (p *MainPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/input_form.qtpl:8
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/input_form.qtpl:8
	p.StreamTitle(qw422016)
//line templates/input_form.qtpl:8
	qt422016.ReleaseWriter(qw422016)
//line templates/input_form.qtpl:8
}

//line templates/input_form.qtpl:8
func (p *MainPage) Title() string {
//line templates/input_form.qtpl:8
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/input_form.qtpl:8
	p.WriteTitle(qb422016)
//line templates/input_form.qtpl:8
	qs422016 := string(qb422016.B)
//line templates/input_form.qtpl:8
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/input_form.qtpl:8
	return qs422016
//line templates/input_form.qtpl:8
}

//line templates/input_form.qtpl:11
func (p *MainPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/input_form.qtpl:11
	qw422016.N().S(`
<form>
    <p><input name="login"> <input type="password" name="pass"></p>
    <p><input type="submit"></p>    
</form>
`)
//line templates/input_form.qtpl:16
}

//line templates/input_form.qtpl:16
func (p *MainPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/input_form.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/input_form.qtpl:16
	p.StreamBody(qw422016)
//line templates/input_form.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line templates/input_form.qtpl:16
}

//line templates/input_form.qtpl:16
func (p *MainPage) Body() string {
//line templates/input_form.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/input_form.qtpl:16
	p.WriteBody(qb422016)
//line templates/input_form.qtpl:16
	qs422016 := string(qb422016.B)
//line templates/input_form.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/input_form.qtpl:16
	return qs422016
//line templates/input_form.qtpl:16
}
